name: NetherCubeElytra
main: com.gmail.justbru00.nethercube.elytra.main.NetherCubeElytra
version: 1.0-RC3
authors: [JustBru00,Justin Brubaker]
softdepend: [HolographicDisplays]
commands:
  elytra:
    description: Command for opening gui.
    aliases: [ely]
  elytraadmin:
    description: The command for admin/test features.
    aliases: [elyadmin]
  elytrabalance:
    description: Command to view your current elytra currency balance.
    aliases: [elybal]   
  elytralobby:
    description: Command to teleport to the elytra lobby and leave the current map.
    aliases: [elylobby] 
  