name: NetherCubeElytra
main: com.gmail.justbru00.nethercube.elytra.main.NetherCubeElytra
version: 1.0-INDEV
authors: [JustBru00,Justin Brubaker]
commands:
  nethercubeelytra:
    description: Command for all features.
    aliases: [nce]
  elytrastats:
    description: Shows your stats for NetherCubeElytra
  